import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :sly_panorama, SlyPanoramaWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  url: [port: 443, scheme: "https"],
  force_ssl: [rewrite_on: [:x_forwarded_proto]],
  check_origin: ["//slypanorama.com", "//www.slypanorama.com"]

# Req client (used by some Swoosh adapters; production mail uses SMTP2GO via `Swoosh.Adapters.SMTP`).
config :swoosh, api_client: Swoosh.ApiClient.Req

#disable email preview being served in production
config :swoosh, serve_mailbox: false, preview_port: 4001

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
